// Command creplay replays Claude Code sessions in a terminal UI.
//
// # Usage
//
//	creplay SESSION_ID [options]
//	creplay -file FILE [options]
//
// The creplay command provides a TUI (terminal user interface) for
// replaying Claude Code sessions. It supports both historical playback
// of completed sessions and real-time streaming of active sessions.
//
// # Arguments
//
//	SESSION_ID
//	    Session ID generated by mksid
//	    Format: timestamp-sorted UUID with git repo context
//
// # Options
//
//	-file string
//	    Read session from file instead of looking up by ID
//	    File should contain NDJSON formatted messages
//
//	-follow
//	    Follow mode: continue watching for new messages (like tail -f)
//	    Useful for real-time monitoring of active sessions
//
//	-speed float
//	    Playback speed multiplier (default 1.0)
//	    Values > 1.0 speed up replay, < 1.0 slow it down
//
// # Session Lookup
//
// When given a session ID, creplay locates the session file using:
//
//   - Standard session storage locations
//   - Git repository context from the session ID
//   - Fallback to current directory search
//
// # Display Modes
//
// The TUI supports multiple display modes:
//
//   - Full session view with message history
//   - Split view showing user and assistant separately
//   - Raw NDJSON view for debugging
//   - Streaming mode with real-time updates
//
// # Keyboard Controls
//
//	q, Ctrl-C    Quit
//	Space        Pause/resume playback
//	↑/↓         Scroll through messages
//	f           Toggle follow mode
//	r           Toggle raw NDJSON view
//	?           Show help
//
// # Examples
//
// Replay a completed session:
//
//	creplay 2024-11-14-abc123-def456
//
// Replay from a file:
//
//	creplay -file session-2024-11-14.ndjson
//
// Follow an active session in real-time:
//
//	SID=$(mksid)
//	echo "query" | cmsg | tee session-$SID.ndjson
//	creplay -follow $SID
//
// Replay at 2x speed:
//
//	creplay -speed 2.0 $SID
//
// # Session File Format
//
// Session files contain NDJSON (newline-delimited JSON) with each line
// representing a message:
//
//	{"type":"user","content":"first message"}
//	{"type":"assistant","content":"first response"}
//	{"type":"user","content":"second message"}
//
// # Streaming and Real-time
//
// The creplay command supports real-time playback:
//
//   - Detects incomplete sessions and waits for updates
//   - Follow mode (-follow) watches for new messages
//   - Gracefully handles corrupted or partial messages
//   - Works with active sessions being written by other tools
//
// # Error Handling
//
// The command handles various error conditions:
//
//   - Missing or invalid session IDs
//   - Corrupted NDJSON data
//   - Incomplete messages in streaming sessions
//   - Session files being written concurrently
//
// # Integration
//
// The creplay command integrates with other cc utilities:
//
//   - Use mksid to generate session IDs
//   - Use cmsg to format messages for sessions
//   - Monitor sessions created by any NDJSON-producing tool
package main
