// Package cc provides core utilities for developing software with Claude Code.
//
// The cc package includes tools for session management, message formatting,
// and session replay capabilities. These utilities are designed to work
// together to support streaming workflows and real-time collaboration.
//
// # Session IDs
//
// Session IDs are generated by the mksid command and are used consistently
// across all cc utilities for session correlation. They are timestamp-sorted
// UUIDs that include:
//
//   - Chronological ordering via timestamp prefix
//   - Git repository context hash from CWD
//   - Reserved space for fork tracking
//
// # Message Format
//
// Messages are formatted as NDJSON (newline-delimited JSON) for streaming
// compatibility. Each line represents a complete Claude message object.
//
// # Streaming Support
//
// All utilities prioritize streaming and real-time compatibility:
//
//   - Input/output via standard streams (stdin/stdout)
//   - NDJSON format for structured data
//   - No unnecessary buffering
//   - Composable via Unix pipes
//
// # Commands
//
// The cc package provides three main commands:
//
//   - mksid: Generate timestamp-sorted session IDs with git context
//   - cmsg: Format stdin as Claude messages (NDJSON/streaming)
//   - creplay: Replay Claude Code sessions in a TUI
//
// # Example Usage
//
// Create a session, format a message, and replay:
//
//	export SID=$(mksid)
//	echo "user input" | cmsg | tee session-$SID.ndjson
//	creplay $SID
//
// Stream multiple messages:
//
//	mksid > session.id
//	echo "first message" | cmsg >> session-$(cat session.id).ndjson
//	echo "second message" | cmsg >> session-$(cat session.id).ndjson
//	creplay $(cat session.id)
package cc
